### ISSUE TITLE
Support for Code Folding

### ISSUE THREAD

**Issue by prajankya** [bobbylight/TokenMakerMaker#4]
TokenMakerMaker doesn't generate code for code Folding..
Changing just the language to something like java and C brings the folding back.

**Comment by bobbylight** [comment]
Code folding isn't inherently tied to TokenMakers, even though it could have been done that way (and arguably should have).

If you want code folding like in existing languages, you can reuse one of the existing `FoldParser` implementations, such as `CurlyFoldParser`, by registering it with the `FoldParserManager` at application startup for your language.  If you want to create custom folding rules, that would be out of scope for TokenMakerMaker since it focuses on syntax highlighting only.
